version: '3.8'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  cassandra-node1:
    image: cassandra
    volumes:
      - ./volumes/cassandra-node1:/var/lib/cassandra
    # environment:
    #   - 'CASSANDRA_SEEDS=cassandra-node2'

  # cassandra-node2:
  #   image: cassandra
  #   volumes:
  #     - ./volumes/cassandra-node2:/var/lib/cassandra
  #   environment:
  #     - 'CASSANDRA_SEEDS=cassandra-node1'

  message-service1:
    image: message-service
    depends_on:
      - cassandra-node1
    ports:
      - 5011:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
      APPID: "1"

  message-service2:
    image: message-service
    depends_on:
      - cassandra-node1
    ports:
      - 5012:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
      APPID: "2"

  message-service3:
    image: message-service
    depends_on:
      - cassandra-node1
    ports:
      - 5013:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
      APPID: "3"
