version: '3.8'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  api-gateway1:
    image: api-gateway
    ports:
      - 5011:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
      APPID: "1"

  api-gateway2:
    image: api-gateway
    ports:
      - 5012:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
      APPID: "2"

  api-gateway3:
    image: api-gateway
    ports:
      - 5013:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
      APPID: "3"

  cassandra-node1:
    image: cassandra
    ports:
      - "7001:7000"
    environment:
      - 'CASSANDRA_SEEDS=cassandra-node2'

  cassandra-node2:
    image: cassandra
    ports:
      - "7002:7000"
    environment:
      - 'CASSANDRA_SEEDS=cassandra-node1'

  message-service1:
    image: message-service
    ports:
      - 5111:5011
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5011"
